---
title: "Exploratory Analysis"
output: 
  html_document:
    toc: true
    toc_float: true

---

This page gives a overview on investigating our dataset.

## Investigation based on borough

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(plotly)
library(patchwork)
library(hexbin)
load("data/cleaned_data.RData")
```

```{r}
df = 
  transformed_rental_income %>% 
  separate(boro_block_lot, into = c("borough", "block", "lot"), sep = "-") %>% 
  mutate(
    borough = case_when(
      borough == "1" ~ "Manhattan",
      borough == "2" ~ "Bronx",
      borough == "3" ~ "Brooklyn",
      borough == "4" ~ "Queens",
      borough == "5" ~ "Staten Island")
    )
```


```{r }
df %>% 
  mutate(borough = fct_reorder(borough, full_market_value)) %>% 
  group_by(borough) %>%
  summarise(
    observations = n()
  ) %>%
  plot_ly(y = ~borough, 
          x = ~observations, 
          color = ~borough, 
          type = "bar", 
          colors = "viridis",
          orientation = 'h') %>%
  layout(title = 'Records in each Borough')
```


```{r}
df %>% 
  group_by(borough) %>%
  summarise(
    mean_value = mean(full_market_value)
  ) %>%
  mutate(borough = fct_reorder(borough, mean_value)) %>% 
  plot_ly(y = ~borough, 
          x = ~mean_value, 
          color = ~borough, 
          type = "bar", 
          colors = "viridis",
          orientation = 'h') %>%
  layout(title = 'Mean Values of each Borough')
```

According to the histogram plot, we can see that the order of mean value is Manhattan, Queens, Brooklyn, Bronx and Staten Island from the highest to the lowest.
Both number and mean value of rentals in Manhattan take the head.


## The proportion of each building classification

```{r}

c_df = as_tibble(table(df['building_classification']))
```

```{r}
plot_ly(c_df, labels = ~building_classification , values = ~n, type = 'pie')
```





