---
title: "Project Proposal"
output: github_document
date: "2022-11-12"
---

### Group Members:

Zizhao Lin zl3263

Zekai Jin zj2357

Qilin Zheng qz2492

Yanling Xue yx2710

Ruiji Pan rp3127

### Tentative Title：

Value the building: how much are the rentals in NYC?

### The motivation for the project:

Everyone who tries to move to New York City is suffering from the high rent of apartments, which inspired us to investigate apartment rentals in this city. We hope our analysis can help the students find a cheaper rental plan.

### The intended final products:

The intended final products include a clearly written report, reproducible code, and a webpage that can be accessed remotely. In the webpage, we hope to include a text introduction to our project and a dashboard to show our exploration towards the data.

### The anticipated data sources:

We plan to use the Cooperative/Condominium Comparable Rental Income Archives from the NYC Department of Finance, which can be accessed through [NYC Open Data](https://data.cityofnewyork.us/City-Government/DOF-Cooperative-Comparable-Rental-Income-Citywide-/myei-c3fa). This dataset is intended to evaluate the price of condominiums or cooperatives buildings in NYC in the same way of evaluating rental apartment.  However, it gives us the chance to take a glance at the rentals. The key variables include `Address`, `Total Units`,    `Year Built`, `Gross SqFt`, `Gross Income` , and `report year`.

### The planned analyses/visualizations:

- Rent distribution and rent trends. (e.g. does covid greatly influence the rent? )

- Factors that may influence the rent. (e.g. address, units, year built)

- Make a map to show the rent in each area of NYC.

- Histograms to show the rent distribution and scatter plots to show the trends.

### Coding Challenges:

- How to convert the building income to rent price?

- Which model is to be used for our regression analysis?

- How to arrange the variables to make clear and deliverable plots?

- How to generate our website to make it clean and attractive?
